import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/fonts.scss";
import "../styles/var.scss";
import "../styles/reset.scss";
import "./globals.scss";
import Header from "@/widgets/Header/Header";
import Footer from "@/widgets/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Театр",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
